<a href="https://codeimmersives.com"><img src = "https://www.codeimmersives.com/wp-content/uploads/2019/09/CodeImmersives_Logo_RGB_NYC_BW.png" width = 400> </a>


<h1 align=center><font size = 5>Agenda</font></h1>

### 
<div class="alert alert-block alert-info" style="margin-top: 20px">

1. [Mean or Average](#0)<br>
2. [Median](#2)<br> 
3. [Mode](#4)<br>     
4. [Max](#6)<br> 
5. [Min](#8)<br> 
6. [Range](#10)<br>    
7. [Weighted Mean](#12)<br> 
8. [Exercise 1](#14)<br>   
9. [Exercise 2](#16)<br>    
10.[Exercise 3](#18)<br>
</div>
<hr>

<h2>Mean or Average</h2><a id="0"></a>
The first basic statistic that we are going to cover is the mean or average.  It is calculated by <br>
adding up all of the values in a data set and dividing by the number of items in the set. <br>
Let's start with a set of high school algebra test scores.  <br>
<br>
91,88,83,84,92,95,88,91,88,86<br>
<br>
In our case we have 10 numbers.  <br>
$\sum_{i=1}^{10} X_i$/10<br>
<br>
Which can be generalized to:
$\sum_{i=1}^{n} X_i$/n<br>
<br>
Above is the mathematical representation of the mean<br>
<br>
Write your python code below is calculate the mean<br>

list = [8,5,3,2,1]
def avarage:
    sum(list)/len(list)
    return avarage

def my_mean(sample)
return sum(sample) / len(sample)

sample = 91,88,83,84,92,95,88,91,88,86
sum(sample) / len(sample)

To get a better idea of the range of our data let's order it from <br>
smallest to largest number<br>

<h4>Question</h4>
How do you order a list in ascending order?

In [ ]:
lst = [8,5,3,2,1]
lst.sort()
print(lst)

[1, 2, 3, 5, 8]

<h4>Question</h4>
How would we sort the same list of grades from largest to smallest?

In [ ]:
lst[::-1]

[8, 5, 3, 2, 1]

In [ ]:
lst.sort(reverse=True)
print(lst)

[8, 5, 3, 2, 1]

<h2>The median</h2><a id="2"></a>
Is the middle number in a series.  It is calculated in 2 different ways<br>
based on the number of items in the data set.<br>
<br>
Even number of items<br>
The median takes the 2 middle numbers in the case of a set of 10 numbers it would be <br>
the 5th and 6th items added together and divided by 2.  In the case of our ordered<br>
final grades it would entail adding (88 + 88 )/ 2 = 88<br>
Which can be generalized to:<br>
$ (X_5$ + $X_6$ )/2<br>
<br>
For an odd number of items the median is the middle number.  <br>

In [150]:
scores = [91,88,83,84,92,95,88,91,88,95]
scores.sort()
print(scores)

if len(scores) % 2 == 1:
    index = int(len(scores)/2)
    oMedian = scores[index]
    print(oMedian)
else:
    indexLeft = int((len(scores)/2) - 1)
    indexRight = indexLeft + 1
    eMedian = (scores[indexLeft] + scores[indexRight]) / 2
    print(eMedian)

[83, 84, 88, 88, 88, 91, 91, 92, 95, 95]
89.5

In [151]:
scores = [91,88,83,84,92,95,88,91,88,86]

# Algorithm for Median

# check the length of list
# sort the list 
    # if length of list is odd 
        # calculate median of odd list 
    # if length of list is even 
        # calculate median of even list 

len(scores) 

# print(scores)
scores.sort()

print(scores)

# what is the median?
    # len of list (which is odd)

# calculating for odd 
if len(scores) % 2 == 1:
    # find the middle index 
    index = int(len(scores)/2)
    oMedian = scores[index]
    print(oMedian)
    
# calculating for even 
if len(scores) % 2 == 0: 
    indexLeft = int((len(scores)/2) - 1)
    indexRight = indexLeft + 1
    eMedian = (scores[indexLeft] + scores[indexRight]) / 2
    print(eMedian)

[83, 84, 86, 88, 88, 88, 91, 91, 92, 95]
88.0

<h2>Exercise</h2>
Calculate the median of the following odd numbered data set:<br>
<code>
    heights = [62, 65, 67, 60, 63]
</code>

<h4>Solution</h4>
Steps<br>
1 - Order the data set from smallest to largest<br>
2 - Calculate the length of the list<br>
3 - If odd numbered take the middle number<br>
4 - If even number of items take the middle 2 number and add them<br>
Then divide by 2<br>

<h2>Exercise</h2>
Take 5 - 10 minutes to develop a object oriented solution<br>
or at least 2 functions<br>
Calculate the mean and median of the following data sets.<br>
Create a class called BaseStatistics<br>
Create a method called calc_mean which takes in a list argument<br>
Create a method called calc_median which takes in a list argument<br>
<code>
fire_flies_per_yard = [22,34,37,14,11,10]<br>
summer_temps = [78, 77, 74, 80, 72]
</code>

In [ ]:
# Function Definitions 
class BaseStatistics():
  def ___init__ (self,lst,x):
    self.lst = lst
    self.x = x
  def calc_mean(lst):
      return sum(lst)/len(lst)    
  def calc_median(lst):
      # finding the median of an odd length list
      if len(lst) % 2 == 1: # checking for odd
          index = int(len(lst)/2) # index of middle element in odd list
          median = lst[index]
      else: # getting midpoint of list that is even
          indexLeft  = int(len(lst)/2) - 1 
          indexRight = indexLeft + 1
          median = (lst[indexLeft] + lst[indexRight]) / 2
      return median

# Does mean need to be sorted?
    # answer is no... but we'll need it for median

# Sorting the list

print("ODD: ", summer_temps)
print("EVEN: ", fire_flies_per_yard)

# Mean calculation of lists
summer_temps = [78, 77, 74, 80, 72]
summer_temps.sort()

stMean = calc_mean(summer_temps)
print("stMean: ", stMean)

fire_flies_per_yard = [22,34,37,14,11,10]
fire_flies_per_yard.sort()

ffMean = calc_mean(fire_flies_per_yard)
print("ffMean: ",ffMean)

# Median calculation of lists
stMedian = calc_median(summer_temps)
print("StMedain: ",stMedian)

ffMedian = calc_median(fire_flies_per_yard)
print("ffMedian: ", ffMedian)

# sorting the list

ODD:  [72, 74, 77, 78, 80]
EVEN:  [10, 11, 14, 22, 34, 37]
stMean:  76.2
ffMean:  21.333333333333332
StMedain:  77
ffMedian:  18.0

<h4>Solution</h4>

<h2>The Mode</h2><a id="4"></a>
The mode represents the most common number in a data set.<br>
A data set could have several modes or no mode at all<br>
For example the number 1 through 10 would not have a mode<br>
<br>
nums = [1,2,3,4,5,6,7,8,9,10]<br>
<br>
Whereas the following data set would have a mode<br>
nums = [3,7,2,5,11,5]<br>
The mode would be 5 because it is repeated twice in this data set.<br>
Before we create a method and add it to out baseStatisics class let's<br>
create a function for the mode<br>

<h2>Exercise</h2>
Create a python function to calculate the mode of the below data set<br>
<code>
summer_temps = [72,77,79,82,84,77,89]
</code>
<br>

<h4>Solution</h4>

In [ ]:

def calc_mode(lst):
    lst.sort()
    modes = {}
    for i in lst:
        if not i in modes:
            modes[i] = 0
        modes[i] += 1    
    print (modes)
    sorted_modes = sorted(modes.items(), key = lambda kv:kv[1], reverse=True)
    print (sorted_modes)
    max_iter = sorted_modes[0][1]
    print(max_iter)
    if max_iter > 1:
      modes = [sorted_modes[i][0] for i,val in enumerate(sorted_modes) if sorted_modes[i][1] == max_iter]
    return 
summer_temps = [72,77,79,82,84,77,89]
calc_mode(summer_temps)

{72: 1, 77: 2, 79: 1, 82: 1, 84: 1, 89: 1}
[(77, 2), (72, 1), (79, 1), (82, 1), (84, 1), (89, 1)]
2

<h2>Question</h2>
How do we sort a dictionary in descending key order?

In [152]:
freq = {1:'9', 2 : '3', 0:'5'}
sorted (freq.keys())

[0, 1, 2]

<H1>EXERCISE</H1>
<p>Create a program that counts the total number of times a nine ('9') <br>
appears in all of number from 100 to 1,000.  For example the number 199 has<br>
2 nines in the number.

In [ ]:
a = 10
b = 1000
nines = {}
for i in range (a, b):
  str_i = str(i)
  count = 0 
  for x in str_i:
    if x == '9':
      count += 1
  # print (i, count)
  nines[i] = count
  # print (nines)
print (nines)

Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

In [ ]:
numbers = [2,7,11,15] 
target = 2

dict_add = ()
for idex, num in enumerate(numbers):
  str_num = str(num)
  add_num = 0 
  for i in str_num:
    add_num += int(i) 
  # print (num, add_num)
  if add_num == target:
    print (idex, num, add_num)

0 2 2
2 11 2

<h4>Exercise</h4>
Return all of the modes for the following data set:<br>
    <code>
    summer_temps = [72,77,79,82,84,77,89,79]
    </code>

<h4>Solution</h4>

Reverse the given integer. Eg: 123 = 321. -345 = -543. -120= -21

In [ ]:
def reverse_num(nums):
  # print(nums)
  for num in nums:
    num_str = str(num)   
    a = num_str[::-1]
    if '-' in a: 
      a = '-' + a.replace('-', '')
    if a[0] == 0:
      a = ('', '0')
  return (a)  
nums =  [123, -345, -120] 
print (reverse_num(nums))

-021

In [ ]:
def reverse(num):
  if num < 0:
    a = int(f”-{str(num)[:0:-1]}“)
  else:
    a = int(str(num)[::-1])
  return a
print(reverse(504))

<h2>Algebra Problem</h2>
A student scores the following on 5 exams:<br>
<code>
grades = [88,86,89, 92, 94]
</code>
What grade do they have to obtain on their next exam to have a<br>
90 average?<br>

<h4>Solution</h4>
To solve this equation we need to set up up like this:<br>
(88, 86, 89, 92, 94 + x)/ 6 = 90<br>
step 1 - multiply both sides by 6 to eliminate the denominator on the right side<br>
step 2 - (88, 86, 89, 92, 94 + x) = 540<br>
step 3 - isolate the x by subtracting 88, 86, 89, 92, 94 which is 449 from both sides<br>
step 4 - x = 540 - 449 = 91<br>

<h2>Minimum</h2><a id="8"></a>
What is the smallest number in our data set?<br>
We can calculate the minimum 2 ways<br>
method 1<br>
sort the list and using slicing give the 1st item<br>
method 2<br>
use the built in python method - min()<br>
<br>
<code>
grades = [88, 86, 89, 92, 94]
</code>

In [ ]:
grades = [88, 86, 89, 92, 94]

print(min(grades))

86

<h2>Maximum</h2><a id="6"></a>
What is the largestest number in our data set?<br>
We can calculate the maximum 2 ways<br>
method 1<br>
sort the list and using slicing give the last item<br>
method 2<br>
use the built in python method - max()<br>
<br>
<code>
grades = [88, 86, 89, 92, 94]
</code>

In [ ]:
grades = [88, 86, 89, 92, 94]

print(max(grades))

94

<h4>Range</h4>
The range is calculated by taking the maximum minus the minimum<br>
<br>
Find the range for:<br>
<code>
grades = [88, 86, 89, 92, 94]
</code>

In [ ]:
grades = [88, 86, 89, 92, 94]
mini = min(grades)
maxi = max(grades)
range = maxi - mini
range

8

<h2>Weighted Mean</h2><a id="12"></a>
The weighted mean is calculated by taking each number in the data set and <br>
multiplying it by a weight which represents its portion of the total result.<br>
The weights must add up to 1 or 100%.  For example let's take our exams and classify<br>
them by exam type of regular exam or midterm or final exam.<br>
regular exam - 12%<br>
regular exam - 12%<br>
regular exam - 12%<br>
regular exam - 12%<br>
regular exam - 12%<br>
midtern 1 - 10%<br>
midtern 2 - 10%<br>
final exam - 20%<br>
<br>
The exam scores are as follows:<br>
regular exams - 88, 84, 89, 92, 90<br>
midterm exams - 87, 84<br>
final exam - 94<br>
<br>
How would you represent this in a data structure and solve the problem?<br>

<h4>Solution</h4>
<code>

</code>

In [ ]:
exams = [88, 84, 89, 92, 90, 87, 84, 94]
porcentage = [.12, .12, .12, .12, .12, .10, .10, .20]

grades = 0 

for i in regular_exams:
  grades += (i*.12)
for i in midterm_exams:
  grades += (i*.10)
for i in final_exam:
  grades += (i*.20)

print (grades)

89.06

<h2>Exercise 1</h2><a id="14"></a>
Go back to your class BaseStatistics and add a method for calculating the:<br>
mode<br>
min<br>
max<br>
range<br>
weighted mean<br>

<h2>Exercise 2</h2><a id="16"></a>
There is a file grades.txt read the file and generate the base statistics for this file<br>

### <h2>Exercise 3</h2><a id="18"></a>
Calculate all of the base statistics for the following different data structure<br>
<code>
class_grades = {'Anton': [88, 78,83,85,87],
               'Rebecca': [92,97,95, 92, 88],
               'Franklin': [77, 78, 73,88, 90],
               'Orin': [88,78,98,92,85],
               'Rose': [90,92,94,96,98]}
</code><br>
Calculate each individuals grade statistics and the class statistics<br>

This notebook is part of a course at www.codeimmersives.com called Data Science. If you accessed this notebook outside the course, you can get more information about this course online by clicking here.

<hr>

Copyright &copy; 2021  Code Immersives